### ISSUE TITLE
Check DG diagrams

### ISSUE THREAD

**Issue by austenjs** [AY2021S2-CS2103-T14-4/tp#296]

**Comment by austenjs** [comment]
UI diagram : 2 multiplicity for TaskListPanel

**Comment by austenjs** [comment]
Multiplicities

**Comment by austenjs** [comment]
Remove Model optional implementation section

**Comment by austenjs** [comment]
VersionedTaskTracker extends TaskTracker

**Comment by austenjs** [comment]
TaskTracker have 2 UniqueTaskList

**Comment by austenjs** [comment]
Create sort activity diagram

**Comment by austenjs** [comment]
state 6 tt3 instead of tt2

**Comment by austenjs** [comment]
delete design consideration of undo/redo

**Comment by austenjs** [comment]
delete proposed data archiving

**Comment by austenjs** [comment]
remove proposed from priority tag

**Comment by austenjs** [comment]
weikiat: user stories at DG
1. Update sort
2. Update description of reminder to be "filtered tasks that are due soon"
3. List
4. Undo/redo
5. DailyTask

**Comment by mrweikiat** [comment]
Edit on DG:
1) Write effort appendix
2) Write manual testing appendix
