### ISSUE TITLE
JSON storage not propagating automatically

### ISSUE THREAD

**Issue by danielonges** [AY2021S2-CS2103-T14-4/tp#82]
I noticed that there was an issue when I tried to delete the JSON file that stores all the data.

Expected behaviour: if there is no existing JSON file, the Storage class is supposed to automatically create sample data in a JSON using TypicalTasks.

Actual behaviour: No such file was being created.

Additional notes: There is an additional tasktracker.json file being created in the root directory. Is this supposed to be the case? Because I thought that this file was only supposed to be created in the /data directory.

Perhaps we can look into this and figure out where the bug is?

**Comment by austenjs** [comment]
Yes, i am confused with the additional tasktracker.json. I check the UserPrefs and the default path is to that tasktracker.json instead of /data

**Comment by danielonges** [comment]
Ok, maybe we can discuss this later? Maybe somebody changed the path accidentally
